# Generated by Django 5.2.11 on 2026-09-16 14:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_discount_type_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Percentage when discount_type is 'percent', otherwise a flat amount.", max_digits=10),
        ),
    ]
