# Generated by Django 5.2.11 on 2026-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], max_length=20, null=True),
        ),
    ]
