# Generated by Django 5.2.11 on 2026-05-20 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyprofile_description_companyprofile_industry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, help_text='e.g., Wholesale local medicines and surgical tools.', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.CharField(blank=True, help_text='e.g., Pharmacy, Grocery, Electronics', max_length=100, null=True),
        ),
    ]
