# Generated by Django 5.2.9 on 2026-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
